spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quanlycntt
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080
app:
  jwt:
    secret: "change-this-to-a-long-random-secret-32-bytes-min"
    expiration: 86400000   # 1 ngày (ms)