server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quanlykhoa
    username: postgres
    password: "123"
  jpa:
    hibernate:
      ddl-auto: validate    
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
